# Generated by Django 5.2.6 on 2026-01-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_contactus_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
